  version: '3.7'

  services:
    bot:
      build: .
      command: sh -c 'python main.py'
      volumes:
        - /home/inspector-data:/app/data
      restart: always
      container_name: inspector-bot